import { createServer } from 'http';
import { Server } from 'socket.io';
import { uniqueNamesGenerator, adjectives, animals } from 'unique-names-generator';
// @ts-ignore — generated by `npm run build` (adapter-node output)
import { handler } from './build/handler.js';

const COLORS = [
	'#f87171',
	'#fb923c',
	'#fbbf24',
	'#a3e635',
	'#34d399',
	'#38bdf8',
	'#818cf8',
	'#a78bfa',
	'#f472b6',
	'#fb7185',
	'#2dd4bf',
	'#facc15',
	'#60a5fa',
	'#c084fc',
	'#f97316',
	'#4ade80',
	'#e879f9',
	'#67e8f9',
	'#fde68a',
	'#a5f3fc'
];

type ClientInfo = { color: string; name: string };

const httpServer = createServer(handler);
const io = new Server(httpServer);

const clients = new Map<string, ClientInfo>();

io.on('connection', (socket) => {
	const color = COLORS[Math.floor(Math.random() * COLORS.length)];
	const name = uniqueNamesGenerator({
		dictionaries: [adjectives, animals],
		length: 2,
		separator: ' '
	});
	clients.set(socket.id, { color, name });

	socket.emit('welcome', { name, color });

	socket.on('cursor', ({ x, y }: { x: number; y: number }) => {
		socket.broadcast.emit('cursor', { id: socket.id, x, y, color, name });
	});

	socket.on('disconnect', () => {
		clients.delete(socket.id);
		socket.broadcast.emit('cursor:leave', { id: socket.id });
	});
});

const port = process.env.PORT ?? 3000;
httpServer.listen(port, () => {
	console.log(`Server running on port ${port}`);
});
